# Generated by Django 4.2.4 on 2023-08-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mess_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.IntegerField(),
        ),
    ]
