# Generated by Django 4.2.4 on 2023-08-30 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mess_app", "0002_alter_member_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="mail",
            new_name="Email",
        ),
    ]
