# Generated by Django 4.2.4 on 2023-08-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mess_app", "0004_meal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="Deposite",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="meal",
            name="Meal",
            field=models.FloatField(),
        ),
    ]
