# Generated by Django 4.2.4 on 2023-08-30 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mess_app", "0005_alter_meal_deposite_alter_meal_meal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="Meal",
            new_name="meals",
        ),
    ]
