# Generated by Django 4.2.4 on 2023-08-30 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mess_app", "0006_rename_meal_meal_meals"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meal",
            old_name="member",
            new_name="Name",
        ),
    ]
