# Generated by Django 4.2.4 on 2023-09-02 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mess_app", "0008_userinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="user",
            new_name="username",
        ),
    ]
